"""add exercise library and routines

Revision ID: 00ded2d7162e
Revises: 1c6061304f8d
Create Date: 2026-08-09 20:08:21.784271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00ded2d7162e'
down_revision: Union[str, None] = '1c6061304f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('primary_muscle', sa.String(length=100), nullable=False),
    sa.Column('secondary_muscles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('equipment', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('setup', sa.Text(), nullable=False),
    sa.Column('execution', sa.Text(), nullable=False),
    sa.Column('cues', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('common_faults', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_exercises_category'), 'library_exercises', ['category'], unique=False)
    op.create_index(op.f('ix_library_exercises_primary_muscle'), 'library_exercises', ['primary_muscle'], unique=False)
    op.create_index(op.f('ix_library_exercises_slug'), 'library_exercises', ['slug'], unique=True)
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.String(length=100), nullable=False),
    sa.Column('day_label', sa.String(length=100), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_goal'), 'routines', ['goal'], unique=False)
    op.create_index(op.f('ix_routines_slug'), 'routines', ['slug'], unique=True)
    op.create_table('routine_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('single', 'superset', 'circuit', name='block_kind'), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('rest_after_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_id', 'order', name='uq_routine_block_order')
    )
    op.create_index(op.f('ix_routine_blocks_routine_id'), 'routine_blocks', ['routine_id'], unique=False)
    op.create_table('block_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.String(length=50), nullable=False),
    sa.Column('load_note', sa.String(length=255), nullable=True),
    sa.Column('tempo', sa.String(length=50), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['routine_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['library_exercises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'order', name='uq_block_exercise_order')
    )
    op.create_index(op.f('ix_block_exercises_block_id'), 'block_exercises', ['block_id'], unique=False)
    op.create_index(op.f('ix_block_exercises_exercise_id'), 'block_exercises', ['exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_block_exercises_exercise_id'), table_name='block_exercises')
    op.drop_index(op.f('ix_block_exercises_block_id'), table_name='block_exercises')
    op.drop_table('block_exercises')
    op.drop_index(op.f('ix_routine_blocks_routine_id'), table_name='routine_blocks')
    op.drop_table('routine_blocks')
    op.drop_index(op.f('ix_routines_slug'), table_name='routines')
    op.drop_index(op.f('ix_routines_goal'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_library_exercises_slug'), table_name='library_exercises')
    op.drop_index(op.f('ix_library_exercises_primary_muscle'), table_name='library_exercises')
    op.drop_index(op.f('ix_library_exercises_category'), table_name='library_exercises')
    op.drop_table('library_exercises')
    # ### end Alembic commands ###
